name: Deploy DockerMulti
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t schnarbiemeows/docker-multi -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true schnarbiemeows/docker-multi npm test

      - run: docker build -t schnarbiemeows/multi-client ./client
      - run: docker build -t schnarbiemeows/multi-nginx ./nginx
      - run: docker build -t schnarbiemeows/multi-server ./server
      - run: docker build -t schnarbiemeows/multi-worker ./worker

      - run: docker push schnarbiemeows/multi-client
      - run: docker push schnarbiemeows/multi-nginx
      - run: docker push schnarbiemeows/multi-server
      - run: docker push schnarbiemeows/multi-worker
